"""One-time (or rarely-run) build step: fetch KaTeX's CSS and font files from
cdnjs and bake a fully self-contained stylesheet -- every @font-face's woff2
url() rewritten to an inline data: URI. Artifact CSP allows <link rel=stylesheet>
only from fonts.googleapis.com, so KaTeX's own CSS can never be loaded via
<link>; and cdnjs (where the fonts actually live) isn't an allowed font-file
host either, so a literal `url(fonts/KaTeX_Main-Regular.woff2)` left in place
would silently fail to load under the real CSP. Baking the fonts in as data:
URIs sidesteps both restrictions -- the result is pasted as literal <style>
content by html.py, never loaded via a network request from the published page.

Run manually: `python -m lecturepipe.publish.build_katex`
Only needs re-running on a deliberate KATEX_VERSION bump.
"""
from __future__ import annotations

import re

import requests

from lecturepipe.config import ROOT

KATEX_VERSION = "0.16.9"
CSS_URL = f"https://cdnjs.cloudflare.com/ajax/libs/KaTeX/{KATEX_VERSION}/katex.min.css"
FONT_URL_TMPL = f"https://cdnjs.cloudflare.com/ajax/libs/KaTeX/{KATEX_VERSION}/{{path}}"
OUT_PATH = ROOT / "lecturepipe" / "publish" / "static" / "katex-inline.css"

# Matches one @font-face's src list. cdnjs serves this CSS minified, e.g.:
#   src:url(fonts/KaTeX_Main-Regular.woff2) format("woff2"),url(...) format("woff"),url(...) format("truetype")}
# -- no space after `src:`, double-quoted format(), and (since src is the
# last declaration in the rule) terminated by the block's closing `}` rather
# than a `;`.
_SRC_LIST_RE = re.compile(r"src:([^;}]+)(?=[;}])")
_URL_RE = re.compile(r"url\(([^)]+)\)\s*format\((['\"])([^'\"]+)\2\)")


def _fetch(path: str) -> bytes:
    r = requests.get(FONT_URL_TMPL.format(path=path), timeout=30)
    r.raise_for_status()
    return r.content


def rebuild() -> None:
    r = requests.get(CSS_URL, timeout=30)
    r.raise_for_status()
    css = r.text

    font_cache: dict[str, str] = {}  # path -> base64

    def _rewrite_src_list(m: re.Match) -> str:
        src_list = m.group(1)
        # keep only the woff2 entry from each @font-face's src list -- a
        # modern Chromium Artifact viewer never needs the woff/ttf fallbacks,
        # and dropping them roughly halves the embedded payload.
        for url, _quote, fmt in _URL_RE.findall(src_list):
            if fmt != "woff2":
                continue
            path = url.strip("'\"")
            if path not in font_cache:
                import base64

                font_cache[path] = base64.b64encode(_fetch(path)).decode("ascii")
            data_uri = f"data:font/woff2;base64,{font_cache[path]}"
            return f"src:url({data_uri}) format(\"woff2\")"
        # no woff2 entry found (shouldn't happen for KaTeX) -- leave as-is
        return m.group(0)

    inlined = _SRC_LIST_RE.sub(_rewrite_src_list, css)

    header = (
        f"/* Self-contained KaTeX {KATEX_VERSION} CSS, fonts inlined as base64 "
        f"data: URIs. Generated by lecturepipe/publish/build_katex.py -- do not "
        f"hand-edit; re-run the script to regenerate on a KaTeX version bump. */\n"
    )
    OUT_PATH.write_text(header + inlined, encoding="utf-8")
    print(f"wrote {OUT_PATH} ({OUT_PATH.stat().st_size / 1024:.0f} KB, "
          f"{len(font_cache)} fonts inlined)")

    remaining = re.findall(r"url\(fonts/[^)]+\)", inlined)
    if remaining:
        print(f"WARNING: {len(remaining)} un-inlined font url() refs remain "
              f"(non-woff2 fallbacks left in place by design, or a pattern miss "
              f"-- inspect): {remaining[:5]}")


if __name__ == "__main__":
    rebuild()
